# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\mille\Downloads\Code\COMP_195 Senior Project\senior-project-spring-2023-web-scraping\CarInfo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1199, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bg_frame = QtWidgets.QFrame(self.centralwidget)
        self.bg_frame.setStyleSheet("QFrame {\n"
"    background-color: #27062D;\n"
"    border-radius: 7px; \n"
"}")
        self.bg_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bg_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bg_frame.setObjectName("bg_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.bg_frame)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.quit_button = QtWidgets.QPushButton(self.bg_frame)
        self.quit_button.setMaximumSize(QtCore.QSize(16, 16))
        self.quit_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.quit_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 11, 68);\n"
"    border-radius: 8px; \n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 11, 68, 150);\n"
"}\n"
"    ")
        self.quit_button.setText("")
        self.quit_button.setObjectName("quit_button")
        self.verticalLayout_2.addWidget(self.quit_button, 0, QtCore.Qt.AlignRight)
        self.main_frame = QtWidgets.QFrame(self.bg_frame)
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.outer_frame = QtWidgets.QFrame(self.main_frame)
        self.outer_frame.setStyleSheet("QFrame{\n"
"    background-color: #AC41D1;\n"
"}")
        self.outer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.outer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outer_frame.setObjectName("outer_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.outer_frame)
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.back_button = QtWidgets.QPushButton(self.outer_frame)
        self.back_button.setMinimumSize(QtCore.QSize(38, 38))
        self.back_button.setMaximumSize(QtCore.QSize(42, 38))
        self.back_button.setSizeIncrement(QtCore.QSize(16, 16))
        self.back_button.setBaseSize(QtCore.QSize(16, 16))
        self.back_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.back_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(181, 84, 215);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(181, 84, 215,150);\n"
"}")
        self.back_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/checkbox.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_button.setIcon(icon)
        self.back_button.setIconSize(QtCore.QSize(38, 38))
        self.back_button.setObjectName("back_button")
        self.verticalLayout_4.addWidget(self.back_button)
        self.inner_frame = QtWidgets.QFrame(self.outer_frame)
        self.inner_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inner_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inner_frame.setObjectName("inner_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.inner_frame)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_main_frame = QtWidgets.QFrame(self.inner_frame)
        self.left_main_frame.setStyleSheet("")
        self.left_main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_main_frame.setObjectName("left_main_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.left_main_frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.upper_left = QtWidgets.QFrame(self.left_main_frame)
        self.upper_left.setStyleSheet("QFrame{\n"
"    background-color: #D9D9D9;\n"
"}")
        self.upper_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.upper_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.upper_left.setObjectName("upper_left")
        self.verticalLayout_5.addWidget(self.upper_left)
        self.lower_left = QtWidgets.QFrame(self.left_main_frame)
        self.lower_left.setMaximumSize(QtCore.QSize(16777215, 200))
        self.lower_left.setStyleSheet("QFrame{\n"
"    background-color: #D9D9D9;\n"
"}")
        self.lower_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lower_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lower_left.setObjectName("lower_left")
        self.verticalLayout_5.addWidget(self.lower_left)
        self.horizontalLayout.addWidget(self.left_main_frame)
        self.right_main_frame = QtWidgets.QFrame(self.inner_frame)
        self.right_main_frame.setStyleSheet("QFrame{\n"
"    background-color: #D9D9D9;\n"
"}")
        self.right_main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_main_frame.setObjectName("right_main_frame")
        self.horizontalLayout.addWidget(self.right_main_frame)
        self.verticalLayout_4.addWidget(self.inner_frame)
        self.verticalLayout_3.addWidget(self.outer_frame)
        self.verticalLayout_2.addWidget(self.main_frame)
        self.verticalLayout.addWidget(self.bg_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
