# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\mille\Downloads\Code\COMP_195 Senior Project\senior-project-spring-2023-web-scraping\filter.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background_frame_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.background_frame_2.setContentsMargins(10, 10, 10, 10)
        self.background_frame_2.setSpacing(0)
        self.background_frame_2.setObjectName("background_frame_2")
        self.background_frame = QtWidgets.QFrame(self.centralwidget)
        self.background_frame.setStyleSheet("QFrame {\n"
"    background-color: #27062D;\n"
"    border-radius: 7px; \n"
"}")
        self.background_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.background_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background_frame.setObjectName("background_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.background_frame)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_main_frame = QtWidgets.QFrame(self.background_frame)
        self.left_main_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.left_main_frame.setMaximumSize(QtCore.QSize(320, 16777215))
        self.left_main_frame.setStyleSheet("QFrame {\n"
"    background-color: #27062D;\n"
"    border-radius: 7px; \n"
"}")
        self.left_main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_main_frame.setObjectName("left_main_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left_main_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logo_frame = QtWidgets.QFrame(self.left_main_frame)
        self.logo_frame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.logo_frame.setStyleSheet("QFrame {\n"
"    background-color: #27062D;\n"
"    border-radius: 7px; \n"
"}")
        self.logo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo_frame.setObjectName("logo_frame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.logo_frame)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.button_home = QtWidgets.QPushButton(self.logo_frame)
        self.button_home.setMinimumSize(QtCore.QSize(0, 0))
        self.button_home.setMaximumSize(QtCore.QSize(1000, 100))
        self.button_home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_home.setStyleSheet("QPushButton { \n"
"    border:none;\n"
"    background-color: #27062D;\n"
"    font-size: 50px; \n"
"    font-weight: bold; \n"
"    font-family: Segoe Print;\n"
"    color: white;\n"
"} \n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(156,39,176);\n"
"}\n"
"\n"
"")
        self.button_home.setObjectName("button_home")
        self.verticalLayout_14.addWidget(self.button_home, 0, QtCore.Qt.AlignTop)
        self.verticalLayout_2.addWidget(self.logo_frame)
        self.filter_frame = QtWidgets.QFrame(self.left_main_frame)
        self.filter_frame.setStyleSheet("QFrame{\n"
"    background-color: #27062D;\n"
"}")
        self.filter_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.filter_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.filter_frame.setObjectName("filter_frame")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.filter_frame)
        self.verticalLayout_15.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_15.setSpacing(2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.inside_filter_frame = QtWidgets.QFrame(self.filter_frame)
        self.inside_filter_frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(146, 91, 156);\n"
"}")
        self.inside_filter_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inside_filter_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inside_filter_frame.setObjectName("inside_filter_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.inside_filter_frame)
        self.verticalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_6.setSpacing(7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.button_submit = QtWidgets.QPushButton(self.inside_filter_frame)
        self.button_submit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_submit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.button_submit.setStyleSheet("QPushButton {\n"
"    background-color: rgb(181, 84, 215);\n"
"    border-radius: 5px; \n"
"    font-size: 26px;\n"
"    font-weight: bold;\n"
"    font-family: Open Sans; \n"
"    color:white\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgba(181, 84, 215,150);\n"
"}")
        self.button_submit.setAutoRepeatDelay(500)
        self.button_submit.setAutoRepeatInterval(0)
        self.button_submit.setObjectName("button_submit")
        self.verticalLayout_6.addWidget(self.button_submit)
        self.scrollArea = QtWidgets.QScrollArea(self.inside_filter_frame)
        self.scrollArea.setStyleSheet("background-color: rgb(146, 91, 156);\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -208, 289, 954))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.price_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.price_frame.setMinimumSize(QtCore.QSize(271, 109))
        self.price_frame.setMaximumSize(QtCore.QSize(16777215, 300))
        self.price_frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(105, 50, 126);\n"
"}")
        self.price_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.price_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.price_frame.setObjectName("price_frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.price_frame)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.price_bar = QtWidgets.QLabel(self.price_frame)
        self.price_bar.setStyleSheet("QLabel {\n"
"    background-color: #B554D7;\n"
"    border-radius: 8px; \n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    font-family: Open Sans; \n"
"    color:white\n"
"} ")
        self.price_bar.setObjectName("price_bar")
        self.verticalLayout_9.addWidget(self.price_bar, 0, QtCore.Qt.AlignTop)
        self.slider_price = QtWidgets.QSlider(self.price_frame)
        self.slider_price.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.slider_price.setStyleSheet("background-color: rgb(105, 50, 126);")
        self.slider_price.setMaximum(100000)
        self.slider_price.setPageStep(1)
        self.slider_price.setSliderPosition(100000)
        self.slider_price.setOrientation(QtCore.Qt.Horizontal)
        self.slider_price.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_price.setTickInterval(1)
        self.slider_price.setObjectName("slider_price")
        self.verticalLayout_9.addWidget(self.slider_price)
        self.price_label = QtWidgets.QLabel(self.price_frame)
        self.price_label.setStyleSheet("QLabel {\n"
"    color:white;\n"
"    font-size:20pt;\n"
"    font-weight:bold;\n"
"}")
        self.price_label.setObjectName("price_label")
        self.verticalLayout_9.addWidget(self.price_label)
        self.verticalLayout_3.addWidget(self.price_frame)
        self.mile_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.mile_frame.setMinimumSize(QtCore.QSize(271, 109))
        self.mile_frame.setMaximumSize(QtCore.QSize(16777215, 200))
        self.mile_frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(105, 50, 126);\n"
"}")
        self.mile_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mile_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mile_frame.setObjectName("mile_frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.mile_frame)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.miles_bar = QtWidgets.QLabel(self.mile_frame)
        self.miles_bar.setStyleSheet("QLabel {\n"
"    background-color: #B554D7;\n"
"    border-radius: 8px; \n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    font-family: Open Sans; \n"
"    color:white;\n"
"} ")
        self.miles_bar.setObjectName("miles_bar")
        self.verticalLayout_10.addWidget(self.miles_bar, 0, QtCore.Qt.AlignTop)
        self.slider_miles = QtWidgets.QSlider(self.mile_frame)
        self.slider_miles.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.slider_miles.setStyleSheet("background-color: rgb(105, 50, 126);")
        self.slider_miles.setMaximum(100000)
        self.slider_miles.setPageStep(1)
        self.slider_miles.setSliderPosition(100000)
        self.slider_miles.setOrientation(QtCore.Qt.Horizontal)
        self.slider_miles.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_miles.setObjectName("slider_miles")
        self.verticalLayout_10.addWidget(self.slider_miles)
        self.mile_label = QtWidgets.QLabel(self.mile_frame)
        self.mile_label.setStyleSheet("QLabel {\n"
"    color:white;\n"
"    font-size:20pt;\n"
"    font-weight:bold;\n"
"}")
        self.mile_label.setObjectName("mile_label")
        self.verticalLayout_10.addWidget(self.mile_label)
        self.verticalLayout_3.addWidget(self.mile_frame)
        self.owner_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.owner_frame.setMinimumSize(QtCore.QSize(271, 109))
        self.owner_frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(105, 50, 126);\n"
"}")
        self.owner_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.owner_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.owner_frame.setObjectName("owner_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.owner_frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.owner_bar = QtWidgets.QLabel(self.owner_frame)
        self.owner_bar.setMinimumSize(QtCore.QSize(53, 24))
        self.owner_bar.setMaximumSize(QtCore.QSize(253, 24))
        self.owner_bar.setStyleSheet("QLabel {\n"
"    background-color: #B554D7;\n"
"    border-radius: 8px; \n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    font-family: Open Sans; \n"
"    color:white;\n"
"} ")
        self.owner_bar.setObjectName("owner_bar")
        self.verticalLayout_5.addWidget(self.owner_bar)
        self.owner_slider = QtWidgets.QSlider(self.owner_frame)
        self.owner_slider.setStyleSheet("background-color: rgb(105, 50, 126);")
        self.owner_slider.setOrientation(QtCore.Qt.Horizontal)
        self.owner_slider.setObjectName("owner_slider")
        self.verticalLayout_5.addWidget(self.owner_slider)
        self.owner_label = QtWidgets.QLabel(self.owner_frame)
        self.owner_label.setStyleSheet("QLabel {\n"
"    color:white;\n"
"    font-size:20pt;\n"
"    font-weight:bold;\n"
"}")
        self.owner_label.setObjectName("owner_label")
        self.verticalLayout_5.addWidget(self.owner_label)
        self.verticalLayout_3.addWidget(self.owner_frame)
        self.accident_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.accident_frame.setMinimumSize(QtCore.QSize(271, 109))
        self.accident_frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(105, 50, 126);\n"
"}")
        self.accident_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.accident_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.accident_frame.setObjectName("accident_frame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.accident_frame)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.accident_bar = QtWidgets.QLabel(self.accident_frame)
        self.accident_bar.setMinimumSize(QtCore.QSize(253, 24))
        self.accident_bar.setMaximumSize(QtCore.QSize(253, 24))
        self.accident_bar.setStyleSheet("QLabel {\n"
"    background-color: #B554D7;\n"
"    border-radius: 8px; \n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    font-family: Open Sans; \n"
"    color:white;\n"
"} ")
        self.accident_bar.setObjectName("accident_bar")
        self.verticalLayout_12.addWidget(self.accident_bar)
        self.yes = QtWidgets.QCheckBox(self.accident_frame)
        self.yes.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    background-color: rgb(105, 50, 126);\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.yes.setObjectName("yes")
        self.buttonGroup_4 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_4.setObjectName("buttonGroup_4")
        self.buttonGroup_4.addButton(self.yes)
        self.verticalLayout_12.addWidget(self.yes)
        self.no = QtWidgets.QCheckBox(self.accident_frame)
        self.no.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    background-color: rgb(105, 50, 126);\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.no.setObjectName("no")
        self.buttonGroup_4.addButton(self.no)
        self.verticalLayout_12.addWidget(self.no)
        self.verticalLayout_3.addWidget(self.accident_frame)
        self.fuel_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.fuel_frame.setMinimumSize(QtCore.QSize(271, 170))
        self.fuel_frame.setMaximumSize(QtCore.QSize(271, 170))
        self.fuel_frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(105, 50, 126);\n"
"}")
        self.fuel_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fuel_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fuel_frame.setObjectName("fuel_frame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.fuel_frame)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.Label = QtWidgets.QLabel(self.fuel_frame)
        self.Label.setMinimumSize(QtCore.QSize(253, 24))
        self.Label.setMaximumSize(QtCore.QSize(253, 24))
        self.Label.setStyleSheet("QLabel {\n"
"    background-color: #B554D7;\n"
"    border-radius: 8px; \n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    font-family: Open Sans; \n"
"    color:white;\n"
"} ")
        self.Label.setObjectName("Label")
        self.verticalLayout_13.addWidget(self.Label)
        self.Gas = QtWidgets.QCheckBox(self.fuel_frame)
        self.Gas.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    background-color: rgb(105, 50, 126);\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.Gas.setObjectName("Gas")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.Gas)
        self.verticalLayout_13.addWidget(self.Gas)
        self.Electric = QtWidgets.QCheckBox(self.fuel_frame)
        self.Electric.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    background-color: rgb(105, 50, 126);\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.Electric.setObjectName("Electric")
        self.buttonGroup_3.addButton(self.Electric)
        self.verticalLayout_13.addWidget(self.Electric)
        self.Diesel = QtWidgets.QCheckBox(self.fuel_frame)
        self.Diesel.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    background-color: rgb(105, 50, 126);\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.Diesel.setObjectName("Diesel")
        self.buttonGroup_3.addButton(self.Diesel)
        self.verticalLayout_13.addWidget(self.Diesel)
        self.Hybrid = QtWidgets.QCheckBox(self.fuel_frame)
        self.Hybrid.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    background-color: rgb(105, 50, 126);\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.Hybrid.setObjectName("Hybrid")
        self.buttonGroup_3.addButton(self.Hybrid)
        self.verticalLayout_13.addWidget(self.Hybrid)
        self.verticalLayout_3.addWidget(self.fuel_frame)
        self.drop_down_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.drop_down_frame.setMinimumSize(QtCore.QSize(0, 300))
        self.drop_down_frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(105, 50, 126);\n"
"}")
        self.drop_down_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.drop_down_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drop_down_frame.setObjectName("drop_down_frame")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.drop_down_frame)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.year_brand_dropdown = QtWidgets.QToolBox(self.drop_down_frame)
        self.year_brand_dropdown.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.year_brand_dropdown.setStyleSheet("QToolBox {\n"
"    background-color: rgb(105, 50, 126);\n"
"    \n"
"}\n"
"\n"
"QToolBox::tab{\n"
"    background-color: #B554D7;\n"
"    border-radius: 8px; \n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    font-family: Open Sans; \n"
"    color:white;\n"
"}\n"
"\n"
"")
        self.year_brand_dropdown.setObjectName("year_brand_dropdown")
        self.brand_title = QtWidgets.QWidget()
        self.brand_title.setGeometry(QtCore.QRect(0, 0, 236, 303))
        self.brand_title.setObjectName("brand_title")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.brand_title)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.brand_check_frame = QtWidgets.QFrame(self.brand_title)
        self.brand_check_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.brand_check_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.brand_check_frame.setObjectName("brand_check_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.brand_check_frame)
        self.verticalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.nis_check = QtWidgets.QCheckBox(self.brand_check_frame)
        self.nis_check.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nis_check.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.nis_check.setObjectName("nis_check")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.nis_check)
        self.verticalLayout_7.addWidget(self.nis_check)
        self.lex_check = QtWidgets.QCheckBox(self.brand_check_frame)
        self.lex_check.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lex_check.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.lex_check.setObjectName("lex_check")
        self.buttonGroup_2.addButton(self.lex_check)
        self.verticalLayout_7.addWidget(self.lex_check)
        self.chev_check = QtWidgets.QCheckBox(self.brand_check_frame)
        self.chev_check.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chev_check.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.chev_check.setObjectName("chev_check")
        self.buttonGroup_2.addButton(self.chev_check)
        self.verticalLayout_7.addWidget(self.chev_check)
        self.ford_check = QtWidgets.QCheckBox(self.brand_check_frame)
        self.ford_check.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ford_check.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.ford_check.setObjectName("ford_check")
        self.buttonGroup_2.addButton(self.ford_check)
        self.verticalLayout_7.addWidget(self.ford_check)
        self.tesla_check = QtWidgets.QCheckBox(self.brand_check_frame)
        self.tesla_check.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tesla_check.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.tesla_check.setObjectName("tesla_check")
        self.buttonGroup_2.addButton(self.tesla_check)
        self.verticalLayout_7.addWidget(self.tesla_check)
        self.bmw_check = QtWidgets.QCheckBox(self.brand_check_frame)
        self.bmw_check.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bmw_check.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.bmw_check.setObjectName("bmw_check")
        self.buttonGroup_2.addButton(self.bmw_check)
        self.verticalLayout_7.addWidget(self.bmw_check)
        self.cad_check = QtWidgets.QCheckBox(self.brand_check_frame)
        self.cad_check.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cad_check.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.cad_check.setObjectName("cad_check")
        self.buttonGroup_2.addButton(self.cad_check)
        self.verticalLayout_7.addWidget(self.cad_check)
        self.honda_check = QtWidgets.QCheckBox(self.brand_check_frame)
        self.honda_check.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.honda_check.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.honda_check.setObjectName("honda_check")
        self.buttonGroup_2.addButton(self.honda_check)
        self.verticalLayout_7.addWidget(self.honda_check)
        self.verticalLayout_4.addWidget(self.brand_check_frame)
        self.year_brand_dropdown.addItem(self.brand_title, "")
        self.year_title = QtWidgets.QWidget()
        self.year_title.setGeometry(QtCore.QRect(0, 0, 236, 443))
        self.year_title.setObjectName("year_title")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.year_title)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.year_frame = QtWidgets.QFrame(self.year_title)
        self.year_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.year_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.year_frame.setObjectName("year_frame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.year_frame)
        self.verticalLayout_11.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_11.setSpacing(5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.year_check = QtWidgets.QCheckBox(self.year_frame)
        self.year_check.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.year_check.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.year_check.setObjectName("year_check")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.year_check)
        self.verticalLayout_11.addWidget(self.year_check)
        self.year_check1 = QtWidgets.QCheckBox(self.year_frame)
        self.year_check1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.year_check1.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.year_check1.setObjectName("year_check1")
        self.buttonGroup.addButton(self.year_check1)
        self.verticalLayout_11.addWidget(self.year_check1)
        self.year_check2 = QtWidgets.QCheckBox(self.year_frame)
        self.year_check2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.year_check2.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.year_check2.setObjectName("year_check2")
        self.buttonGroup.addButton(self.year_check2)
        self.verticalLayout_11.addWidget(self.year_check2)
        self.year_check3 = QtWidgets.QCheckBox(self.year_frame)
        self.year_check3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.year_check3.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.year_check3.setObjectName("year_check3")
        self.buttonGroup.addButton(self.year_check3)
        self.verticalLayout_11.addWidget(self.year_check3)
        self.year_check4 = QtWidgets.QCheckBox(self.year_frame)
        self.year_check4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.year_check4.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.year_check4.setObjectName("year_check4")
        self.buttonGroup.addButton(self.year_check4)
        self.verticalLayout_11.addWidget(self.year_check4)
        self.year_check5 = QtWidgets.QCheckBox(self.year_frame)
        self.year_check5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.year_check5.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.year_check5.setObjectName("year_check5")
        self.buttonGroup.addButton(self.year_check5)
        self.verticalLayout_11.addWidget(self.year_check5)
        self.year_check6 = QtWidgets.QCheckBox(self.year_frame)
        self.year_check6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.year_check6.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.year_check6.setObjectName("year_check6")
        self.buttonGroup.addButton(self.year_check6)
        self.verticalLayout_11.addWidget(self.year_check6)
        self.year_check7 = QtWidgets.QCheckBox(self.year_frame)
        self.year_check7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.year_check7.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.year_check7.setObjectName("year_check7")
        self.buttonGroup.addButton(self.year_check7)
        self.verticalLayout_11.addWidget(self.year_check7)
        self.year_check8 = QtWidgets.QCheckBox(self.year_frame)
        self.year_check8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.year_check8.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.year_check8.setObjectName("year_check8")
        self.buttonGroup.addButton(self.year_check8)
        self.verticalLayout_11.addWidget(self.year_check8)
        self.year_check9 = QtWidgets.QCheckBox(self.year_frame)
        self.year_check9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.year_check9.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.year_check9.setObjectName("year_check9")
        self.buttonGroup.addButton(self.year_check9)
        self.verticalLayout_11.addWidget(self.year_check9)
        self.year_check10 = QtWidgets.QCheckBox(self.year_frame)
        self.year_check10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.year_check10.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.year_check10.setObjectName("year_check10")
        self.buttonGroup.addButton(self.year_check10)
        self.verticalLayout_11.addWidget(self.year_check10)
        self.year_check11 = QtWidgets.QCheckBox(self.year_frame)
        self.year_check11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.year_check11.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.year_check11.setObjectName("year_check11")
        self.buttonGroup.addButton(self.year_check11)
        self.verticalLayout_11.addWidget(self.year_check11)
        self.verticalLayout_8.addWidget(self.year_frame)
        self.year_brand_dropdown.addItem(self.year_title, "")
        self.verticalLayout_16.addWidget(self.year_brand_dropdown)
        self.verticalLayout_3.addWidget(self.drop_down_frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.verticalLayout_15.addWidget(self.inside_filter_frame)
        self.verticalLayout_2.addWidget(self.filter_frame)
        self.horizontalLayout.addWidget(self.left_main_frame)
        self.right_main_frame = QtWidgets.QFrame(self.background_frame)
        self.right_main_frame.setMaximumSize(QtCore.QSize(10000, 800))
        self.right_main_frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.right_main_frame.setStyleSheet("QFrame{\n"
"    background-color: #27062D;\n"
"}")
        self.right_main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_main_frame.setObjectName("right_main_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.right_main_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.upper_frame = QtWidgets.QFrame(self.right_main_frame)
        self.upper_frame.setMinimumSize(QtCore.QSize(0, 50))
        self.upper_frame.setMaximumSize(QtCore.QSize(16777215, 55))
        self.upper_frame.setStyleSheet("QFrame{\n"
"    background-color: #27062D;\n"
"}")
        self.upper_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.upper_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.upper_frame.setObjectName("upper_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.upper_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_filter = QtWidgets.QPushButton(self.upper_frame)
        self.button_filter.setMinimumSize(QtCore.QSize(38, 38))
        self.button_filter.setMaximumSize(QtCore.QSize(38, 38))
        self.button_filter.setSizeIncrement(QtCore.QSize(16, 16))
        self.button_filter.setBaseSize(QtCore.QSize(16, 16))
        self.button_filter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_filter.setStyleSheet("QPushButton {\n"
"    background-color: rgb(181, 84, 215);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(181, 84, 215,150);\n"
"}")
        self.button_filter.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/checkbox.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_filter.setIcon(icon)
        self.button_filter.setIconSize(QtCore.QSize(38, 38))
        self.button_filter.setObjectName("button_filter")
        self.horizontalLayout_2.addWidget(self.button_filter)
        self.search_bar = QtWidgets.QLineEdit(self.upper_frame)
        self.search_bar.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.search_bar.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(154, 103, 180);\n"
"    opacity: 0.5;\n"
"    border-radius: 8px;\n"
"    font-size: 30px;\n"
"    color:white    ;\n"
"    font-family: Open Sans;\n"
"}\n"
"\n"
"")
        self.search_bar.setObjectName("search_bar")
        self.horizontalLayout_2.addWidget(self.search_bar)
        self.button_search = QtWidgets.QPushButton(self.upper_frame)
        self.button_search.setMinimumSize(QtCore.QSize(38, 38))
        self.button_search.setMaximumSize(QtCore.QSize(38, 38))
        self.button_search.setSizeIncrement(QtCore.QSize(16, 16))
        self.button_search.setBaseSize(QtCore.QSize(16, 16))
        self.button_search.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_search.setStyleSheet("QPushButton {\n"
"    background-color: rgb(181, 84, 215);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(181, 84, 215,150);\n"
"}")
        self.button_search.setText("")
        self.button_search.setIconSize(QtCore.QSize(30, 30))
        self.button_search.setObjectName("button_search")
        self.horizontalLayout_2.addWidget(self.button_search)
        self.button_refresh = QtWidgets.QPushButton(self.upper_frame)
        self.button_refresh.setMinimumSize(QtCore.QSize(38, 38))
        self.button_refresh.setMaximumSize(QtCore.QSize(38, 38))
        self.button_refresh.setSizeIncrement(QtCore.QSize(16, 16))
        self.button_refresh.setBaseSize(QtCore.QSize(16, 16))
        self.button_refresh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_refresh.setStyleSheet("QPushButton {\n"
"    background-color: rgb(181, 84, 215);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(181, 84, 215,150);\n"
"}")
        self.button_refresh.setText("")
        self.button_refresh.setIconSize(QtCore.QSize(32, 32))
        self.button_refresh.setObjectName("button_refresh")
        self.horizontalLayout_2.addWidget(self.button_refresh)
        self.button_update = QtWidgets.QPushButton(self.upper_frame)
        self.button_update.setMinimumSize(QtCore.QSize(38, 38))
        self.button_update.setMaximumSize(QtCore.QSize(38, 38))
        self.button_update.setSizeIncrement(QtCore.QSize(16, 16))
        self.button_update.setBaseSize(QtCore.QSize(16, 16))
        self.button_update.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_update.setStyleSheet("QPushButton {\n"
"    background-color: rgb(181, 84, 215);\n"
"    border-radius: 8px; \n"
"    font: 63 16pt \"Sitka Text Semibold\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(181, 84, 215,150);\n"
"}")
        self.button_update.setText("")
        self.button_update.setIconSize(QtCore.QSize(32, 32))
        self.button_update.setObjectName("button_update")
        self.horizontalLayout_2.addWidget(self.button_update)
        self.button_quit = QtWidgets.QPushButton(self.upper_frame)
        self.button_quit.setMinimumSize(QtCore.QSize(16, 16))
        self.button_quit.setMaximumSize(QtCore.QSize(17, 17))
        self.button_quit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_quit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.button_quit.setAutoFillBackground(False)
        self.button_quit.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 11, 68);\n"
"    border-radius: 8px; \n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 11, 68, 150);\n"
"}\n"
"    ")
        self.button_quit.setText("")
        self.button_quit.setObjectName("button_quit")
        self.horizontalLayout_2.addWidget(self.button_quit, 0, QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.upper_frame)
        self.car_infor_frame = QtWidgets.QFrame(self.right_main_frame)
        self.car_infor_frame.setStyleSheet("QFrame{ \n"
"    background-color: rgb(140, 104, 152);\n"
"}")
        self.car_infor_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.car_infor_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.car_infor_frame.setObjectName("car_infor_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.car_infor_frame)
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cdt = QtWidgets.QTableWidget(self.car_infor_frame)
        self.cdt.setMaximumSize(QtCore.QSize(1165, 16777215))
        self.cdt.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cdt.setStyleSheet("QTableWidget{\n"
"    background-color: #c0c0c0;\n"
"    border: 1px solid rgb(129, 66, 255);\n"
"    color:  rgb(93, 47, 163);\n"
"    selection-background-color:  rgb(93, 47, 163);\n"
"    selection-color: #FFF;\n"
"    \n"
"    font: 63 11pt \"Segoe UI Variable Display Semib\";\n"
"    font-weight:bold;\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.cdt.setObjectName("cdt")
        self.cdt.setColumnCount(0)
        self.cdt.setRowCount(0)
        self.horizontalLayout_3.addWidget(self.cdt)
        self.inventory = QtWidgets.QFrame(self.car_infor_frame)
        self.inventory.setMinimumSize(QtCore.QSize(0, 0))
        self.inventory.setMaximumSize(QtCore.QSize(0, 16777215))
        self.inventory.setStyleSheet("QFrame{\n"
"    background-color: rgb(65, 37, 81);\n"
"}")
        self.inventory.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.inventory.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inventory.setObjectName("inventory")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.inventory)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.inven_label = QtWidgets.QLabel(self.inventory)
        self.inven_label.setMaximumSize(QtCore.QSize(1165, 16777215))
        self.inven_label.setStyleSheet("QLabel{\n"
"    color:white;\n"
"    font: 48pt \"Tw Cen MT Condensed Extra Bold\";\n"
"    text-align:center;\n"
"}")
        self.inven_label.setObjectName("inven_label")
        self.horizontalLayout_4.addWidget(self.inven_label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_3.addWidget(self.inventory)
        self.verticalLayout.addWidget(self.car_infor_frame)
        self.horizontalLayout.addWidget(self.right_main_frame)
        self.background_frame_2.addWidget(self.background_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.year_brand_dropdown.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_home.setText(_translate("MainWindow", "UCR"))
        self.button_submit.setText(_translate("MainWindow", "Filter"))
        self.price_bar.setText(_translate("MainWindow", " PRICE"))
        self.price_label.setText(_translate("MainWindow", "$ 100000"))
        self.miles_bar.setText(_translate("MainWindow", " MILES DRIVEN"))
        self.mile_label.setText(_translate("MainWindow", "100000 Miles"))
        self.owner_bar.setText(_translate("MainWindow", " Number of Owner"))
        self.owner_label.setText(_translate("MainWindow", "0"))
        self.accident_bar.setText(_translate("MainWindow", "Accident"))
        self.yes.setAccessibleName(_translate("MainWindow", "True"))
        self.yes.setText(_translate("MainWindow", "Yes"))
        self.no.setAccessibleName(_translate("MainWindow", "False"))
        self.no.setText(_translate("MainWindow", "No"))
        self.Label.setText(_translate("MainWindow", " Fuel Type"))
        self.Gas.setText(_translate("MainWindow", "Gas"))
        self.Electric.setText(_translate("MainWindow", "Electric"))
        self.Diesel.setText(_translate("MainWindow", "Diesel"))
        self.Hybrid.setText(_translate("MainWindow", "Hybrid"))
        self.nis_check.setAccessibleName(_translate("MainWindow", "NISSAN"))
        self.nis_check.setText(_translate("MainWindow", "Nissan"))
        self.lex_check.setAccessibleName(_translate("MainWindow", "LEXUS"))
        self.lex_check.setText(_translate("MainWindow", "Lexus"))
        self.chev_check.setAccessibleName(_translate("MainWindow", "CHEVROLET"))
        self.chev_check.setText(_translate("MainWindow", "Chevrolet"))
        self.ford_check.setAccessibleName(_translate("MainWindow", "FORD"))
        self.ford_check.setText(_translate("MainWindow", "Ford"))
        self.tesla_check.setAccessibleName(_translate("MainWindow", "TESLA"))
        self.tesla_check.setText(_translate("MainWindow", "Tesla"))
        self.bmw_check.setAccessibleName(_translate("MainWindow", "BMW"))
        self.bmw_check.setText(_translate("MainWindow", "BMW"))
        self.cad_check.setAccessibleName(_translate("MainWindow", "CADILLAC"))
        self.cad_check.setText(_translate("MainWindow", "Cadillac"))
        self.honda_check.setAccessibleName(_translate("MainWindow", "HONDA"))
        self.honda_check.setText(_translate("MainWindow", "Honda"))
        self.year_brand_dropdown.setItemText(self.year_brand_dropdown.indexOf(self.brand_title), _translate("MainWindow", "BRAND"))
        self.year_check.setText(_translate("MainWindow", "2010"))
        self.year_check1.setText(_translate("MainWindow", "2011"))
        self.year_check2.setText(_translate("MainWindow", "2012"))
        self.year_check3.setText(_translate("MainWindow", "2013"))
        self.year_check4.setText(_translate("MainWindow", "2014"))
        self.year_check5.setText(_translate("MainWindow", "2015"))
        self.year_check6.setText(_translate("MainWindow", "2016"))
        self.year_check7.setText(_translate("MainWindow", "2017"))
        self.year_check8.setText(_translate("MainWindow", "2018"))
        self.year_check9.setText(_translate("MainWindow", "2019"))
        self.year_check10.setText(_translate("MainWindow", "2020"))
        self.year_check11.setText(_translate("MainWindow", "2021"))
        self.year_brand_dropdown.setItemText(self.year_brand_dropdown.indexOf(self.year_title), _translate("MainWindow", "YEAR"))
        self.inven_label.setText(_translate("MainWindow", "This page is still under construction "))
