# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\mille\Downloads\Code\COMP_195 Senior Project\senior-project-spring-2023-web-scraping\FilterScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background_frame_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.background_frame_2.setContentsMargins(10, 10, 10, 10)
        self.background_frame_2.setSpacing(0)
        self.background_frame_2.setObjectName("background_frame_2")
        self.background_frame = QtWidgets.QFrame(self.centralwidget)
        self.background_frame.setStyleSheet("QFrame {\n"
"    background-color: #27062D;\n"
"    border-radius: 7px; \n"
"}")
        self.background_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.background_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background_frame.setObjectName("background_frame")
        self.quit_button = QtWidgets.QPushButton(self.background_frame)
        self.quit_button.setGeometry(QtCore.QRect(1160, 5, 16, 16))
        self.quit_button.setMinimumSize(QtCore.QSize(16, 16))
        self.quit_button.setMaximumSize(QtCore.QSize(17, 17))
        self.quit_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.quit_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 11, 68);\n"
"    border-radius: 8px; \n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 11, 68, 150);\n"
"}\n"
"    ")
        self.quit_button.setText("")
        self.quit_button.setObjectName("quit_button")
        self.SearchBar = QtWidgets.QLineEdit(self.background_frame)
        self.SearchBar.setGeometry(QtCore.QRect(200, 20, 750, 35))
        self.SearchBar.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(144,104,140);\n"
"    border-radius: 8px;\n"
"    font-size: 30px;\n"
"    color:white    ;\n"
"    font-family: Open Sans;\n"
"}\n"
"\n"
"")
        self.SearchBar.setObjectName("SearchBar")
        self.search_button = QtWidgets.QPushButton(self.background_frame)
        self.search_button.setGeometry(QtCore.QRect(960, 20, 35, 35))
        self.search_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(181, 84, 215);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(181, 84, 215,150);\n"
"}")
        self.search_button.setText("")
        self.search_button.setObjectName("search_button")
        self.Seach_Icon = QtWidgets.QFrame(self.background_frame)
        self.Seach_Icon.setGeometry(QtCore.QRect(965, 25, 15, 15))
        self.Seach_Icon.setMinimumSize(QtCore.QSize(15, 15))
        self.Seach_Icon.setMaximumSize(QtCore.QSize(15, 15))
        self.Seach_Icon.setStyleSheet("QFrame {\n"
"    background-color: rgb(181,84,215);\n"
"    border: 2px solid rgb(255, 255, 255);\n"
"    border-radius: 7px; \n"
"}\n"
"\n"
"QFrame:hover{\n"
"    background-color: rgba(181,84,215,150);\n"
"    border: 2px solid rgba(181,84,215,150);\n"
"}\n"
"\n"
"\n"
"")
        self.Seach_Icon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Seach_Icon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Seach_Icon.setObjectName("Seach_Icon")
        self.FilterBarArea = QtWidgets.QScrollArea(self.background_frame)
        self.FilterBarArea.setGeometry(QtCore.QRect(10, 110, 271, 551))
        self.FilterBarArea.setMinimumSize(QtCore.QSize(0, 200))
        self.FilterBarArea.setMaximumSize(QtCore.QSize(500, 1000))
        self.FilterBarArea.setStyleSheet("QScrollArea {\n"
"    background-color: rgb(144,104,140);\n"
"    border-radius: 8px; \n"
"} ")
        self.FilterBarArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.FilterBarArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.FilterBarArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.FilterBarArea.setWidgetResizable(True)
        self.FilterBarArea.setObjectName("FilterBarArea")
        self.main_scroll_wheel = QtWidgets.QWidget()
        self.main_scroll_wheel.setGeometry(QtCore.QRect(0, 0, 271, 551))
        self.main_scroll_wheel.setStyleSheet("background-color: rgb(144,104,140);\n"
"border-radius: 10px; \n"
"")
        self.main_scroll_wheel.setObjectName("main_scroll_wheel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_scroll_wheel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.price_bar = QtWidgets.QLabel(self.main_scroll_wheel)
        self.price_bar.setStyleSheet("QLabel {\n"
"    background-color: #B554D7;\n"
"    border-radius: 8px; \n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    font-family: Open Sans; \n"
"    color:white\n"
"} ")
        self.price_bar.setObjectName("price_bar")
        self.verticalLayout.addWidget(self.price_bar)
        self.price_area = QtWidgets.QScrollArea(self.main_scroll_wheel)
        self.price_area.setStyleSheet("QScrollArea {\n"
"    background-color: red;;\n"
"    border-radius: 8px; \n"
"} ")
        self.price_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.price_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.price_area.setWidgetResizable(True)
        self.price_area.setObjectName("price_area")
        self.price_scroll_wheel = QtWidgets.QWidget()
        self.price_scroll_wheel.setGeometry(QtCore.QRect(0, 0, 253, 156))
        self.price_scroll_wheel.setStyleSheet("QWidget {\n"
"    background-color: rgb(164,104,140);\n"
"}")
        self.price_scroll_wheel.setObjectName("price_scroll_wheel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.price_scroll_wheel)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.price_check1 = QtWidgets.QCheckBox(self.price_scroll_wheel)
        self.price_check1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.price_check1.setTabletTracking(True)
        self.price_check1.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.price_check1.setObjectName("price_check1")
        self.verticalLayout_2.addWidget(self.price_check1)
        self.price_check2 = QtWidgets.QCheckBox(self.price_scroll_wheel)
        self.price_check2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.price_check2.setTabletTracking(True)
        self.price_check2.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.price_check2.setObjectName("price_check2")
        self.verticalLayout_2.addWidget(self.price_check2)
        self.price_check3 = QtWidgets.QCheckBox(self.price_scroll_wheel)
        self.price_check3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.price_check3.setTabletTracking(True)
        self.price_check3.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.price_check3.setObjectName("price_check3")
        self.verticalLayout_2.addWidget(self.price_check3)
        self.price_check4 = QtWidgets.QCheckBox(self.price_scroll_wheel)
        self.price_check4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.price_check4.setTabletTracking(True)
        self.price_check4.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.price_check4.setObjectName("price_check4")
        self.verticalLayout_2.addWidget(self.price_check4)
        self.price_area.setWidget(self.price_scroll_wheel)
        self.verticalLayout.addWidget(self.price_area)
        self.miles_bar = QtWidgets.QLabel(self.main_scroll_wheel)
        self.miles_bar.setStyleSheet("QLabel {\n"
"    background-color: #B554D7;\n"
"    border-radius: 8px; \n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    font-family: Open Sans; \n"
"    color:white;\n"
"} ")
        self.miles_bar.setObjectName("miles_bar")
        self.verticalLayout.addWidget(self.miles_bar)
        self.miles_area = QtWidgets.QScrollArea(self.main_scroll_wheel)
        self.miles_area.setStyleSheet("QScrollArea {\n"
"    background-color: red;;\n"
"    border-radius: 8px; \n"
"} ")
        self.miles_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.miles_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.miles_area.setWidgetResizable(True)
        self.miles_area.setObjectName("miles_area")
        self.miles_scroll_wheel = QtWidgets.QWidget()
        self.miles_scroll_wheel.setGeometry(QtCore.QRect(0, 0, 253, 156))
        self.miles_scroll_wheel.setStyleSheet("QWidget {\n"
"    background-color: rgb(164,104,140);\n"
"}")
        self.miles_scroll_wheel.setObjectName("miles_scroll_wheel")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.miles_scroll_wheel)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.miles_check1 = QtWidgets.QCheckBox(self.miles_scroll_wheel)
        self.miles_check1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.miles_check1.setTabletTracking(True)
        self.miles_check1.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.miles_check1.setObjectName("miles_check1")
        self.verticalLayout_3.addWidget(self.miles_check1)
        self.miles_check2 = QtWidgets.QCheckBox(self.miles_scroll_wheel)
        self.miles_check2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.miles_check2.setTabletTracking(True)
        self.miles_check2.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.miles_check2.setObjectName("miles_check2")
        self.verticalLayout_3.addWidget(self.miles_check2)
        self.miles_check3 = QtWidgets.QCheckBox(self.miles_scroll_wheel)
        self.miles_check3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.miles_check3.setTabletTracking(True)
        self.miles_check3.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.miles_check3.setObjectName("miles_check3")
        self.verticalLayout_3.addWidget(self.miles_check3)
        self.miles_check4 = QtWidgets.QCheckBox(self.miles_scroll_wheel)
        self.miles_check4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.miles_check4.setTabletTracking(True)
        self.miles_check4.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.miles_check4.setObjectName("miles_check4")
        self.verticalLayout_3.addWidget(self.miles_check4)
        self.miles_area.setWidget(self.miles_scroll_wheel)
        self.verticalLayout.addWidget(self.miles_area)
        self.year_bar = QtWidgets.QLabel(self.main_scroll_wheel)
        self.year_bar.setStyleSheet("QLabel {\n"
"    background-color: #B554D7;\n"
"    border-radius: 8px; \n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    font-family: Open Sans; \n"
"    color:white;\n"
"} ")
        self.year_bar.setObjectName("year_bar")
        self.verticalLayout.addWidget(self.year_bar)
        self.year_area = QtWidgets.QScrollArea(self.main_scroll_wheel)
        self.year_area.setStyleSheet("QScrollArea {\n"
"    background-color: red;;\n"
"    border-radius: 8px; \n"
"} ")
        self.year_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.year_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.year_area.setWidgetResizable(True)
        self.year_area.setObjectName("year_area")
        self.year_scroll_wheel = QtWidgets.QWidget()
        self.year_scroll_wheel.setGeometry(QtCore.QRect(0, 0, 253, 156))
        self.year_scroll_wheel.setStyleSheet("QWidget {\n"
"    background-color: rgb(164,104,140);\n"
"}")
        self.year_scroll_wheel.setObjectName("year_scroll_wheel")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.year_scroll_wheel)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.year_check1 = QtWidgets.QCheckBox(self.year_scroll_wheel)
        self.year_check1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.year_check1.setTabletTracking(True)
        self.year_check1.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.year_check1.setObjectName("year_check1")
        self.verticalLayout_4.addWidget(self.year_check1)
        self.year_check2 = QtWidgets.QCheckBox(self.year_scroll_wheel)
        self.year_check2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.year_check2.setTabletTracking(True)
        self.year_check2.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.year_check2.setObjectName("year_check2")
        self.verticalLayout_4.addWidget(self.year_check2)
        self.year_check3 = QtWidgets.QCheckBox(self.year_scroll_wheel)
        self.year_check3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.year_check3.setTabletTracking(True)
        self.year_check3.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.year_check3.setObjectName("year_check3")
        self.verticalLayout_4.addWidget(self.year_check3)
        self.year_check4 = QtWidgets.QCheckBox(self.year_scroll_wheel)
        self.year_check4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.year_check4.setTabletTracking(True)
        self.year_check4.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.year_check4.setObjectName("year_check4")
        self.verticalLayout_4.addWidget(self.year_check4)
        self.year_area.setWidget(self.year_scroll_wheel)
        self.verticalLayout.addWidget(self.year_area)
        self.brand_bar = QtWidgets.QLabel(self.main_scroll_wheel)
        self.brand_bar.setStyleSheet("QLabel {\n"
"    background-color: #B554D7;\n"
"    border-radius: 8px; \n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    font-family: Open Sans; \n"
"    color:white;\n"
"} ")
        self.brand_bar.setObjectName("brand_bar")
        self.verticalLayout.addWidget(self.brand_bar)
        self.brand_area = QtWidgets.QScrollArea(self.main_scroll_wheel)
        self.brand_area.setStyleSheet("QScrollArea {\n"
"    background-color: red;;\n"
"    border-radius: 8px; \n"
"} ")
        self.brand_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brand_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.brand_area.setWidgetResizable(True)
        self.brand_area.setObjectName("brand_area")
        self.year_scroll_wheel_2 = QtWidgets.QWidget()
        self.year_scroll_wheel_2.setGeometry(QtCore.QRect(0, 0, 253, 228))
        self.year_scroll_wheel_2.setStyleSheet("QWidget {\n"
"    background-color: rgb(164,104,140);\n"
"}")
        self.year_scroll_wheel_2.setObjectName("year_scroll_wheel_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.year_scroll_wheel_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.brand_check = QtWidgets.QCheckBox(self.year_scroll_wheel_2)
        self.brand_check.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.brand_check.setTabletTracking(True)
        self.brand_check.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.brand_check.setObjectName("brand_check")
        self.verticalLayout_6.addWidget(self.brand_check)
        self.brand_check1 = QtWidgets.QCheckBox(self.year_scroll_wheel_2)
        self.brand_check1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.brand_check1.setTabletTracking(True)
        self.brand_check1.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.brand_check1.setObjectName("brand_check1")
        self.verticalLayout_6.addWidget(self.brand_check1)
        self.brand_check5 = QtWidgets.QCheckBox(self.year_scroll_wheel_2)
        self.brand_check5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.brand_check5.setTabletTracking(True)
        self.brand_check5.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.brand_check5.setObjectName("brand_check5")
        self.verticalLayout_6.addWidget(self.brand_check5)
        self.brand_check2 = QtWidgets.QCheckBox(self.year_scroll_wheel_2)
        self.brand_check2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.brand_check2.setTabletTracking(True)
        self.brand_check2.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.brand_check2.setObjectName("brand_check2")
        self.verticalLayout_6.addWidget(self.brand_check2)
        self.brand_check4 = QtWidgets.QCheckBox(self.year_scroll_wheel_2)
        self.brand_check4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.brand_check4.setTabletTracking(True)
        self.brand_check4.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.brand_check4.setObjectName("brand_check4")
        self.verticalLayout_6.addWidget(self.brand_check4)
        self.brand_check3 = QtWidgets.QCheckBox(self.year_scroll_wheel_2)
        self.brand_check3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.brand_check3.setTabletTracking(True)
        self.brand_check3.setStyleSheet("QCheckBox::indicator{ \n"
"    width:25px;\n"
"    height:25px; \n"
"    background-color:white;\n"
"    border-radius: 8px; \n"
"}\n"
"\n"
"QCheckBox {\n"
"    font-size: 25px;\n"
"    spacing:15px;\n"
"    color:white;\n"
"    font-weight:bold;\n"
"    font-family: Open Sans; \n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color:rgb(255, 108, 235)\n"
"}")
        self.brand_check3.setObjectName("brand_check3")
        self.verticalLayout_6.addWidget(self.brand_check3)
        self.brand_area.setWidget(self.year_scroll_wheel_2)
        self.verticalLayout.addWidget(self.brand_area)
        self.FilterBarArea.setWidget(self.main_scroll_wheel)
        self.FilterBar = QtWidgets.QLabel(self.background_frame)
        self.FilterBar.setGeometry(QtCore.QRect(10, 70, 271, 30))
        self.FilterBar.setStyleSheet("QLabel {\n"
"    background-color: #B554D7;\n"
"    border-radius: 8px; \n"
"    font-size: 27px;\n"
"    font-weight: bold;\n"
"    font-family: Open Sans; \n"
"    color:white;\n"
"} ")
        self.FilterBar.setObjectName("FilterBar")
        self.Car_Infor_Area = QtWidgets.QScrollArea(self.background_frame)
        self.Car_Infor_Area.setGeometry(QtCore.QRect(290, 70, 881, 591))
        self.Car_Infor_Area.setWidgetResizable(True)
        self.Car_Infor_Area.setObjectName("Car_Infor_Area")
        self.car_scroll_wheel = QtWidgets.QWidget()
        self.car_scroll_wheel.setGeometry(QtCore.QRect(0, 0, 881, 591))
        self.car_scroll_wheel.setStyleSheet("QWidget {\n"
"    background-color: rgb(167, 105, 171);\n"
"}")
        self.car_scroll_wheel.setObjectName("car_scroll_wheel")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.car_scroll_wheel)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cdt = QtWidgets.QTableWidget(self.car_scroll_wheel)
        self.cdt.setObjectName("cdt")
        self.cdt.setColumnCount(0)
        self.cdt.setRowCount(0)
        self.verticalLayout_5.addWidget(self.cdt)
        self.Car_Infor_Area.setWidget(self.car_scroll_wheel)
        self.Hbutton = QtWidgets.QPushButton(self.background_frame)
        self.Hbutton.setGeometry(QtCore.QRect(50, 0, 151, 51))
        self.Hbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Hbutton.setStyleSheet("QPushButton { \n"
"    border:none;\n"
"    background-color: #27062D;\n"
"    font-size: 60px; \n"
"    font-weight: bold; \n"
"    font-family: Segoe Print;\n"
"    color: white;\n"
"} \n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(156,39,176);\n"
"}")
        self.Hbutton.setObjectName("Hbutton")
        self.quit_button.raise_()
        self.SearchBar.raise_()
        self.search_button.raise_()
        self.FilterBarArea.raise_()
        self.FilterBar.raise_()
        self.Seach_Icon.raise_()
        self.Car_Infor_Area.raise_()
        self.Hbutton.raise_()
        self.background_frame_2.addWidget(self.background_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.price_bar.setText(_translate("MainWindow", "   PRICE"))
        self.price_check1.setAccessibleName(_translate("MainWindow", "$lt 5000"))
        self.price_check1.setText(_translate("MainWindow", "<$5000"))
        self.price_check2.setAccessibleName(_translate("MainWindow", "5000 10000"))
        self.price_check2.setText(_translate("MainWindow", "$5000-10000"))
        self.price_check3.setAccessibleName(_translate("MainWindow", "10000 15000"))
        self.price_check3.setText(_translate("MainWindow", "$10000-15000"))
        self.price_check4.setAccessibleName(_translate("MainWindow", "$gt 15000"))
        self.price_check4.setText(_translate("MainWindow", ">$15000"))
        self.miles_bar.setText(_translate("MainWindow", "MILES DRIVEN"))
        self.miles_check1.setAccessibleName(_translate("MainWindow", "$lt 5000"))
        self.miles_check1.setText(_translate("MainWindow", "<5000 "))
        self.miles_check2.setAccessibleName(_translate("MainWindow", "5000 9999"))
        self.miles_check2.setText(_translate("MainWindow", "5000 -9999"))
        self.miles_check3.setAccessibleName(_translate("MainWindow", "10000 15000"))
        self.miles_check3.setText(_translate("MainWindow", "10000 -15000 "))
        self.miles_check4.setAccessibleName(_translate("MainWindow", "$gt 15000"))
        self.miles_check4.setText(_translate("MainWindow", ">15000"))
        self.year_bar.setText(_translate("MainWindow", "YEAR"))
        self.year_check1.setAccessibleName(_translate("MainWindow", "2000 2005"))
        self.year_check1.setText(_translate("MainWindow", "2000 - 2005"))
        self.year_check2.setAccessibleName(_translate("MainWindow", "2006 2011"))
        self.year_check2.setText(_translate("MainWindow", "2006 - 2011"))
        self.year_check3.setAccessibleName(_translate("MainWindow", "2012 2017"))
        self.year_check3.setText(_translate("MainWindow", "2012 - 2017"))
        self.year_check4.setAccessibleName(_translate("MainWindow", "2017 2022"))
        self.year_check4.setText(_translate("MainWindow", "2017 - 2022"))
        self.brand_bar.setText(_translate("MainWindow", "BRAND"))
        self.brand_check.setAccessibleName(_translate("MainWindow", "FORD"))
        self.brand_check.setText(_translate("MainWindow", "Ford"))
        self.brand_check1.setAccessibleName(_translate("MainWindow", "CHEVROLET"))
        self.brand_check1.setText(_translate("MainWindow", "Chevrolet"))
        self.brand_check5.setAccessibleName(_translate("MainWindow", "CADILLAC"))
        self.brand_check5.setText(_translate("MainWindow", "Cadillac"))
        self.brand_check2.setAccessibleName(_translate("MainWindow", "BMW"))
        self.brand_check2.setText(_translate("MainWindow", "BMW"))
        self.brand_check4.setAccessibleName(_translate("MainWindow", "NISSAN"))
        self.brand_check4.setText(_translate("MainWindow", "Nissan"))
        self.brand_check3.setAccessibleName(_translate("MainWindow", "LEXUS"))
        self.brand_check3.setText(_translate("MainWindow", "Lexus"))
        self.FilterBar.setText(_translate("MainWindow", "          FILTER"))
        self.Hbutton.setText(_translate("MainWindow", "UCR"))
import resource_rc
